### ISSUE TITLE
支持vite2

### ISSUE THREAD

**Issue by agileago** [xuxihai123/vite-plugin-mockit#1]
vite2插件server的api已经改成connect中间件风格了

**Comment by haixuxu** [comment]
使用1.0.0 版本。 使用express风格编写。

[mock列表](https://github.com/xuxihai123/vite-plugin-mockit/blob/master/test/fixtures/data.js)
[mock对象](https://github.com/xuxihai123/vite-plugin-mockit/blob/master/test/fixtures/entry.js)

**Comment by agileago** [comment]
大赞

**Comment by agileago** [comment]
@xuxihai123  添加上类型支持会不会更好

**Comment by haixuxu** [comment]
@agileago 类型，ts？

**Comment by agileago** [comment]
对的

**Comment by agileago** [comment]
@xuxihai123  https://github.com/vitejs/vite/blob/main/packages/vite/CHANGELOG.md#breaking-changes
`server`的api改名字了，现在启动项目的话会有warning

**Comment by haixuxu** [comment]
感觉app=>middlewares , [ViteDevServer](https://github.com/vitejs/vite/blob/809d4bd3bf62d3bc6b35f182178922d2ab2175f1/packages/vite/src/node/server/index.ts#L157) 这改的太不友好了，等vite 稳定了再做支持！

**Comment by agileago** [comment]
@xuxihai123 vite2 正式发布了

**Comment by haixuxu** [comment]
@agileago 62354174f1e33711df9bdfe402cd0a4a10110340
